### ISSUE TITLE
Please add English 

### ISSUE THREAD

**Issue by homersimpsons** [scoute-dich/Weather#1]
Well, I'm not German and I don't know how to speak German so I can't understand your app, I'm interesting in a weather app but an English version would be great please 😃

**Comment by Fale** [comment]
+1

**Comment by scoute-dich** [comment]
Is it ok, when I just add English as new locale, and translate the strings?

**Comment by homersimpsons** [comment]
Yeah, in 'app/src/main/res' you need to add a folder : 'values-en' and a file 'strings.xml' with the English strings inside. 
Note: Default values will be those available in 'values' folder, then it's maybe better to switch 'en' and 'ge' values. 
I think that if you create a file 'strings-en.xml' in 'app/src/main/res/values' it works too.

**Comment by scoute-dich** [comment]
I will do it next week. ;-)

**Comment by Primokorn** [comment]
+1 can we have weather for other countries?

**Comment by scoute-dich** [comment]
added english

@Primokorn you can search for every city, if you open the "Lesezeichen|Suche" menunin app drawer. You can save searched cities than as bookmarks. The probem is known (see #2).
