### ISSUE TITLE
Settings crash at 4.4.4 (Kit Kat)

### ISSUE THREAD

**Issue by raschix** [scoute-dich/Weather#14]
When the settings menu accessed, the app crashed on Android 4.4.4

**Comment by scoute-dich** [comment]
Did you make a fresh install or an update? Are the settings working in earlier versions? Or are the settings working some days before this bug appears?

Perhaps clearing application data or uninstalling and a fresh install can solve the problem.

I don't have a phone with Kikat installed. So I can't test it...

**Comment by raschix** [comment]
I have tested the version 3.5 from F-Droid and 3.7 from Play Store with a fresh install and clear data. Nothing works. On my second device (Android 7.1.1) are no problems.

**Comment by scoute-dich** [comment]
Can you provide a logcat of the bug?

**Comment by raschix** [comment]
I don't know if that enough.

03-18 13:21:00.242 I/ActivityManager(466): START u0 {cmp=de.baumann.weather/.Screen_Main (has extras)} from pid 27479
03-18 13:21:00.273 I/dalvikvm(27479): Could not find method android.view.Window.setStatusBarColor, referenced from method de.baumann.weather.Screen_Main.onCreate
03-18 13:21:00.390 I/dalvikvm(27479): Could not find method android.app.Activity.checkSelfPermission, referenced from method de.baumann.weather.helper.helpers.grantPermissionsStorage
03-18 13:21:00.390 I/dalvikvm(27479): Could not find method android.text.Html.fromHtml, referenced from method de.baumann.weather.helper.helpers.textSpannable
03-18 13:21:00.874 I/ActivityManager(466): Displayed de.baumann.weather/.Screen_Main: +620ms
03-18 13:21:02.984 I/ActivityManager(466): START u0 {cmp=de.baumann.weather/.helper.Settings} from pid 27479
03-18 13:21:03.249 E/AndroidRuntime(27479): Process: de.baumann.weather, PID: 27479
03-18 13:21:03.257 W/ActivityManager(466):   Force finishing activity de.baumann.weather/.helper.Settings
03-18 13:21:03.765 W/ActivityManager(466): Activity pause timeout for ActivityRecord{42b81108 u0 de.baumann.weather/.helper.Settings t177 f}
03-18 13:21:04.507 I/ActivityManager(466): Process de.baumann.weather (pid 27479) has died.
03-18 13:21:04.515 I/WindowState(466): WIN DEATH: Window{42810ec8 u0 de.baumann.weather/de.baumann.weather.helper.Settings}
03-18 13:21:04.515 I/WindowState(466): WIN DEATH: Window{447c3358 u0 de.baumann.weather/de.baumann.weather.Screen_Main}

**Comment by scoute-dich** [comment]
Works version 3.7 from F-Droid?

**Comment by raschix** [comment]
No. The last version which works was v3.4. The changelog from v3.5 says "improved: settings screen". This certainly breaks the settings on KitKat.

**Comment by scoute-dich** [comment]
I think I found the bug. Can you please check the attached apk file and report if the bug is closed? As said, I have no device with KitKat.

I made a zip-file, since it is not allowed to attach apk-files.

Thanks
Gaukler Faun
[app-release.apk.zip](https://github.com/scoute-dich/Weather/files/871893/app-release.apk.zip)

**Comment by raschix** [comment]
This APK works. Thanks for the fix.

**Comment by scoute-dich** [comment]
Thanks for testing. I'll release the update these days.
