### ISSUE TITLE
Allow to reorganize the default cities

### ISSUE THREAD

**Issue by Ablu** [scoute-dich/Weather#2]
Hi,

This app looks like it has some potential :)
I just wonder how i could save my city/bookmark to the list of cities in the left menu. Preferably so that it is the default overview being displayed if i open the app.

**Comment by paulle** [comment]
Very nice app, but I'm missing a possibility to delete the default cities and store my preference cities.

**Comment by scoute-dich** [comment]
At the moment there is no possibility to save the bookmarks in the drawer menu. I don't know how to load the saved bookmarks dynamically in the drawer. Even if I knew, the next problem would be to load the hourly and the trend forecast dynamically... also it would be useful to implement "on click listener" t9 set it as default, to edit the title of the bookmark or to delete it...

**Comment by scoute-dich** [comment]
If someone has ideas... let it know... I'm not a real developer. I only had some ideas and got them work with some research.

**Comment by Ablu** [comment]
The app is looking for even if you are "not a real developer" :+1: 
I will see if i can contribute this somewhen. But I am pretty busy until next week at least. So I am not sure when / if I get around it.

**Comment by scoute-dich** [comment]
I would be glad to get some help, because, if I'm honest, I also want to get the mentioned features implemented.

**Comment by mirabilos** [comment]
As it currently is, it's almost useless. A browsr bookmark can do better, if one has the correct URL, that is.

**Comment by scoute-dich** [comment]
In next release it is possible either to load bookmark list on start or the most top bookmark. It will be also possible to edit bookmarks.

It will not be possible to change the order of bookmarks. And I can't load the bookmark list in the app drawer. Instead you will be able to reach the bookmark list by swiping left or right from the webview.
