### ISSUE TITLE
Feature Request: Adding WeatherPro (MeteoGroup)

### ISSUE THREAD

**Issue by neolovich** [scoute-dich/Weather#20]
Hello!
According to my investigations (read a view articles and tests & treid different apps about years) the WeatherPro app has the best predictions. They offer also a website so maybe it is possible to add this site to this app? Would be nice to have an Open Source app that makes access possible to this site.
http://www.weathercast.co.uk/

If it is possible or not. Anyway: Thanks for your work :+1:

**Comment by scoute-dich** [comment]
I'll stay with wetterdienst.de. In my opinion it's more accurate for the region where I live. But thanks for your interest.
