### ISSUE TITLE
Support NOAA datafeed

### ISSUE THREAD

**Issue by CeaVi** [scoute-dich/Weather#24]
Great to have a weather app that relies on free and public sources like DWD only!

It would be cool to enable for the NOAA API, too, especially handy when traveling. There seem to be multiple API versions, some random links below:

https://www.weather.gov/documentation/services-web-api
https://forecast-v3.weather.gov/documentation
https://www.ncdc.noaa.gov/cdo-web/webservices
https://www.ncdc.noaa.gov/data-access

**Comment by scoute-dich** [comment]
I don't know how to implement such things. The app is mainly for me and my family. I'm just sharing it. Since I have also other (more important projects), I don't have the time. Thanks for your interest.
