### ISSUE TITLE
Prevent duplicate bookmarks

### ISSUE THREAD

**Issue by lovebdsobuj** [scoute-dich/Weather#3]
If URL exits on Bookmark database, then alert message will show "URL already saved into Bookmarks!".

**Comment by scoute-dich** [comment]
I finally found a solution and well implement it on next update (If it's still from interest).

**Comment by lovebdsobuj** [comment]
Implement it on next update, will be good thing.

**Comment by scoute-dich** [comment]
Ok, done.
