### ISSUE TITLE
Can't set more than one bookmark in 4.5.2

### ISSUE THREAD

**Issue by uli-on** [scoute-dich/Weather#31]
If one user-defined bookmark is set I've no chance to define any more, it simply doesn't appear in the bm list. 

After deleting the first one, on creating a different(!) one, the previous bookmark with its URL and its old, previous name is back, the new one never appears. Oh, and it's always the 6 hour preview for the selected city, that appears after deleting No. 1, although the hourly preview was shown while creating the 2nd bookmark.

Android 6.0.1, Moto G flavour

**Comment by scoute-dich** [comment]
Since we're now in version 4.8 please reopen, if issue is still present.
