### ISSUE TITLE
android:progressBackgroundTintMode works not good in API level < 23

### ISSUE THREAD

**Issue by john2020star** [scoute-dich/Weather#33]
Hi,

I have tried to build your app, and found there is a compatibility in the ProgressBar of MainActivity.

In the file `content_main.xml`, you declare a ProgressBar as 
`    <ProgressBar
        android:layout_alignParentBottom="true"
        android:minHeight="4dip"
        android:maxHeight="4dip"
        android:layout_width="fill_parent"
        android:layout_height="wrap_content"
        style="@android:style/Widget.ProgressBar.Horizontal"
        android:progressBackgroundTint="@color/colorPrimary"
        android:progressBackgroundTintMode="src_over"
        android:progressTint="@color/colorAccent"
        android:id="@+id/progressBar" />`

Notice that android:progressBackgroundTintMode="src_over" works not good below API 23, to fix this you may avoid using this attribute. See the screenshot below.

API 23
<img width="407" alt="image" src="https://user-images.githubusercontent.com/62385383/80307212-3b9dea00-87fa-11ea-8296-bb84d1ac6717.png">

API 22
<img width="310" alt="image" src="https://user-images.githubusercontent.com/62385383/80307233-4e182380-87fa-11ea-8df4-8f6fdc8c88c2.png">

**Comment by john2020star** [comment]
I would like to submit a pull request to help you fix this problem.

**Comment by scoute-dich** [comment]
I removed the line. Thanks.
