### ISSUE TITLE
Swiping between overwiew, hourly, forecast

### ISSUE THREAD

**Issue by Cnqu6doa2bn** [scoute-dich/Weather#36]
First of all thank you for your wonderful app!
Is there a possibility that you can add again swiping between the weather forcasts (overiew, hour, daily,...)?
The Icons on the bottoms are quite small (for some people) and it would be much easier to have a gesture like swiping left and right like in the older version 4.3.

**Comment by scoute-dich** [comment]
With next update you can swipe on the title bar to switch. You can also swipe top/bottom to scroll down/up.
