### ISSUE TITLE
Weather Warnings

### ISSUE THREAD

**Issue by NadineThouroghby** [scoute-dich/Weather#37]
Thank you so much for your wonderful app!
Would it be possible to implement warnings from the DWD (e.g. storm, slickness, flood waters, etc.)?

**Comment by scoute-dich** [comment]
You can save any DWD site as bookmark inside the app. For example https://www.dwd.de/DE/wetter/warnungen/warnWetter_node.html

The app only shows the websites of the dwd and wetterdienst.de.
