### ISSUE TITLE
Changing to hourly and 10-days preview maybe broken

### ISSUE THREAD

**Issue by chhinze** [scoute-dich/Weather#39]
When switching to houlry ("stündlich") and 10-days ("10-Tage") preview, the app redirected me to the start page (`m.wetterdienst.de/stuendlich` or `m.wetterdienst.de/10-Tage`) without keeping the location. Is this a problem for anyone else?
I guessed this to be an URL problem and adding a `/` between town and following URL parts in  [l.189 of `MainActivity.java`](https://github.com/scoute-dich/Weather/blob/11e605947cfb9373a8d90878a068433fc3f054fd/app/src/main/java/de/baumann/weather/MainActivity.java#L189) fixed it for me.

```java
// old code:
action_overView = "http://m.wetterdienst.de/Wetter/" + town;

// changed one
action_overView = "http://m.wetterdienst.de/Wetter/" + town + "/";
```
Thanks a lot for this app!

**Comment by scoute-dich** [comment]
I'll display the original website of wetterdienst.de with next update. There are buttons to switch between the different forecasts. So I'll remove the forecast menu at the bottom. This will be obsolete with next update.

**Comment by chhinze** [comment]
Awesome! Thank you.
