### ISSUE TITLE
Internationalisation

### ISSUE THREAD

**Issue by manu-p** [scoute-dich/Weather#4]
Hi, I'm quite happy with Weather 2.3 so far, but since I'm not German speaking I struggle a bit with most of the displayed words in German, except menus in English.

I'm speaking about "PLZ/Ort eingeben", "Wetter", "Überblick", "stündlich", "10 Tage", "Montag", "Dienstag", etc...

Is there a way to get these words translated in English ? In French ? In...

Thanks.

**Comment by scoute-dich** [comment]
Since weather uses only webview to display a website it isn't possible to change the content of displayed websites in the app. The menu belongs to the app and is translatable. Sorry :-(
