### ISSUE TITLE
Favorite bookmark not distinguished

### ISSUE THREAD

**Issue by SebiderSushi** [scoute-dich/Weather#41]
With FOSS Weather version 4.9.1 from F-Droid, the bookmark list provides no distiguishing feature for the currently favorited bookmark.

It would be nice to have an intuitive star icon at the right end or similar to communicate the currently selected favorite bookmark.
This is particularly desirable to deliver instant feedback when changing the favorited bookmark.

**Comment by scoute-dich** [comment]
You can see the actual favorite at the top of the bookmarklist. It changes, when you set a new favorite.

**Comment by SebiderSushi** [comment]
Wow i must be blind, thank you! 😅
