### ISSUE TITLE
Splash screen image too small for high resolution phone screens

### ISSUE THREAD

**Issue by Sofoca** [scoute-dich/Weather#5]
Probably (?) this is intentional. Is the problem the original image resolution?

![screenshot_20160606-184013](https://cloud.githubusercontent.com/assets/8494954/15830000/834ab75a-2c16-11e6-9668-cfb90035d856.png)

**Comment by scoute-dich** [comment]
What is your screen resolution?

**Comment by Sofoca** [comment]
Nexus 5X with 1080p display.

**Comment by scoute-dich** [comment]
I will fix it in next release. It could take a couple of weeks (busy at school/work). But I won't forget it. No big thing...

**Comment by scoute-dich** [comment]
I think it's fixed in next update. Please report back.

**Comment by Sofoca** [comment]
Works now!

**Comment by scoute-dich** [comment]
Ok. Good, there should be a new big update in the next days. If there are problems again you're welcome to report them.
