### ISSUE TITLE
Play Store

### ISSUE THREAD

**Issue by Sofoca** [scoute-dich/Weather#6]
Hello there @scoute-dich, 
with your permission I would publish my [fork](https://github.com/Sofoca/Weather) on Google Play. Free, of course, and with reference to the original developer. I will try to keep the fork updated with changes made here and take it down if I fail to do so for good.

**Comment by scoute-dich** [comment]
If reference to my app, keep it free and publish it also under gpl license, it would be ok for me.

**Comment by scoute-dich** [comment]
If you published the app, can you please give me the link to play store?

**Comment by Sofoca** [comment]
Sure thing! Would you mind providing a logo in 512 x 512 (or is it already in the repo and I did not find it?)?

**Comment by scoute-dich** [comment]
![weather_512](https://cloud.githubusercontent.com/assets/3949944/19927353/a97dbcf8-a0f9-11e6-972a-20b51dc6fcac.png)

Here it is!

**Comment by Sofoca** [comment]
Thanks, I will post any updates here.

**Comment by Sofoca** [comment]
Outch, didn't want to close the issue.

**Comment by Sofoca** [comment]
Outch, didn't want to close the issue. I will inform you here once the app is on the store.

**Comment by Sofoca** [comment]
A beta version is available on https://play.google.com/apps/testing/de.baumann.weather right now. Let me know if you have any comments. Otherwise, I will improve the store page and localize it to English, then publish the app.

**Comment by scoute-dich** [comment]
Nice.

Off topic: how can I create a developer account without credit card? Is it possible?

**Comment by scoute-dich** [comment]
Perhaps you can add the information, that the app shows data from wetterdienst.de and the DWD...

**Comment by Sofoca** [comment]
Regarding off topic: No, I think this is actually not possible. You do need a credit card. 

Good idea, I will add that information.

**Comment by scoute-dich** [comment]
I close the issue, but when there are any news, you can comment here.
