### ISSUE TITLE
No difference in Übersicht, Stündlich and Trend

### ISSUE THREAD

**Issue by Basti1512** [scoute-dich/Weather#7]
I assume that there should be differences in the content of the three Pages Übersicht, Stündlich and Trend. Unfortunately it isn't, all three pages show the same content on my Nexus 5 running Android 6.0.1.

Best regards
Basti

**Comment by scoute-dich** [comment]
Yes there should be differences between the three tabs. You should click the magnifier icon in the main screnn, then search for a location and then save the "Übersicht" tab as bookmark. Then when you return to the main screen you can delete the default bookmark by long pressing and open the new saved location.

I hope this explanation solved the issue.

Regards Gaukler Faun

**Comment by Basti1512** [comment]
You are right, I overdid it! I tried to save a bookmark for each tab and that doesn't work.

**Comment by scoute-dich** [comment]
No problem. ;-)
